package:
  name: metroscreen
  version: "0.1.0"
  
channels:
  - conda-forge
  - bioconda
  - liulab-dfci
  - bioturing
  - defaults

source:
  path: /fs/home/tangke/metabolism/tool/MetroSCREEN

build:
  number: 0
  preserve_egg_dir: True
  script: |
    Rscript install_missing_packages.r

requirements:
  build:
    - python <3.9
    - setuptools
    - r-base >=4.1.3
    - r-seurat>=4.3.0, <5.0.0
    - r-devtools
    - lisa2
    - r-dplyr
    - r-tidyr
    - r-ggplot2
    - r-ggpubr
    - r-rcolorbrewer
    - r-rpref
    - r-igraph
    - r-robustrankaggreg
    - r-ggraph
    - r-reshape2
    - bioconductor-rbgl
    - bioconductor-gsva
    - bioconductor-complexheatmap
    - bioconductor-limma
  run:
    - python >=3.8
    - r-base >=4.1.3
    - r-seurat>=4.3.0, <5.0.0
    - r-devtools
    - lisa2
    - r-dplyr
    - r-tidyr
    - r-ggplot2
    - r-ggpubr
    - r-rcolorbrewer
    - r-rpref
    - r-igraph
    - r-robustrankaggreg
    - r-ggraph
    - r-reshape2
    - bioconductor-rbgl
    - bioconductor-gsva
    - bioconductor-complexheatmap
    - bioconductor-limma
    
    

about:
  home: https://github.com/Tangke98/MetroSCREEN
  summary: Metabolite and their associated extrinsic and intrinsic regulators screening based on transcriptomic data.
  doc_url: https://metroscreen-rtd-rutorial.readthedocs.io/en/latest/
  dev_url: https://github.com/Tangke98/MetroSCREEN